### ISSUE TITLE
heapdump进程阻塞

### ISSUE THREAD

**Issue by flylinda** [hyj1991/xprofiler#59]
heapdump进程阻塞问题原因是在哪里呢

**Comment by hyj1991** [comment]
序列化在主线程操作

**Comment by XiaocongDong** [comment]
> 序列化在主线程操作

大佬你好，我看了一下Xprofiler的源码，有两个问题想请教一下

1. 发现CPUProfiler::StartProfiling和CPUProfiler::StopProfiling的操作都是通过NotifyJSThread的方式放回到主线程里面执行，想知道为什么不在WatcherThread里面执行呢？是因为要访问到v8的数据结构所以才放到主线程吗？
2. NotifyJsThread的实现问题，我看到大佬是先用isolate->RequestInterrupt的方式将callback传递给v8，然后调用uv_async_send唤起lib_uv的event_loop执行，想问一下RequestInterrupt之后一定要用uv_async_send吗？这样做的原因是什么呢？
